iter5
shestooy/go-metrics pull request #5
Opened 2024-08-10 13:45 UTC by shestooy

2024-08-11 14:17 UTC, shestooy commented
Привет, прошу прощения название некоторых коммитов, буду исправляться)

2024-08-12 21:53 UTC, Bazys requested changes
main - точка входа - тут минимум кода

2024-08-12 21:53 UTC, Bazys commented on cmd/agent/main.go
> +func getAllMetrics() []Metric {
давай выносить всю логику из main.
Это точка входа - здесь минимум кода - только для запуска.

2024-08-12 21:53 UTC, Bazys commented on cmd/server/main.go
> +func GetRouter() chi.Router {
тоже перенсти в internal

2024-08-12 21:53 UTC, Bazys commented on internal/handlers/handlers.go
> +func GetAllMetrics(res http.ResponseWriter, req *http.Request) {
Параметр функции, названный `req`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `req` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-08-18 12:56 UTC, Bazys approved these changes
щас заворачивать не буду, но к следующему разу исправить

2024-08-18 12:56 UTC, Bazys commented on cmd/server/main.go
> +	flags.ParseServerFlags()
```suggestion
	flags.ParseServer()
```
flags - уже есть, зачем повторять?

2024-08-18 12:56 UTC, Bazys commented on internal/agent/agent.go
> +	metrics := make([]m.Metric, 0)
не очень рационально с точки зрения работы с памятью, но во втрой половине будет pptof - там посмотришь

2024-08-18 12:56 UTC, Bazys commented on internal/flags/flags.go
> +		ReportInterval, _ = strconv.ParseInt(envReportInterval, 10, 64)
почему ошибки не обрабатываем?

2024-08-18 16:39 UTC, shestooy commented on cmd/server/main.go
> +	flags.ParseServerFlags()
тут немного не понял, что исправить

2024-08-18 16:46 UTC, merged