iter9
shestooy/go-metrics pull request #9
Opened 2024-08-28 18:36 UTC by shestooy

2024-08-30 14:13 UTC, nburunova requested changes

2024-08-30 14:13 UTC, nburunova commented on internal/server/httpserver/httpserver.go
> +
горутину startSaveMetrics не останавливаем, надо бы ее тоже явно остановить, иначе начнет вызывать сохранение на закрытом сторадже

2024-08-30 14:13 UTC, nburunova commented on internal/agent/agent.go
> +			SetBody(metric.Compress()).
если Compress() отработает с ошибкой, то пустое боди будет. Лучше чтобы compress возвращал ошибку

2024-08-31 16:55 UTC, shestooy commented
чутка с названием последнего коммита пролетел, бывает

2024-09-02 08:09 UTC, nburunova approved these changes

2024-09-02 12:21 UTC, merged